### ISSUE TITLE
AirDrop icon missing in UIActivityViewController

### ISSUE THREAD

**Issue by jakubpetrik** [Affirm/affirm-merchant-sdk-ios#101]
![IMG_DD262A765686-1](https://user-images.githubusercontent.com/560958/127002852-5033cd3a-15b4-4127-b2d9-e7673ae0cd98.jpeg)

Steps to reproduce:
1. Create new Xcode project
2. Add button with action:
```swift
@IBAction func share() {
    let shareSheet = UIActivityViewController(activityItems: [URL(string: "http://placekitten.com/800/600")!], applicationActivities: nil)
    present(shareSheet, animated: true, completion: nil)
}
```
3. Launch the app, tap the share button and observe share sheet (AirDrop icon is fully visible)
4. Add `AffirmSDK` pod to project
5. Repeat step 3 and observe AirDrop icon (badge visible, but icon is missing)

**Comment by kukosk** [comment]
We're also seeing this exact same bug in our project. When we remove the SDK, the icon normally appears in the sheet. Any updates on this?
