### ISSUE TITLE
AffirmPromoRequest should include page_type

### ISSUE THREAD

**Issue by diptibele** [Affirm/affirm-merchant-sdk-ios#11]
Ex: https://sandbox.affirm.com/api/promos/v2/ARQBLCL7NAMBTZ7F?field=ala&amount=50000&logo_color=blue&logo_type=logo&page_type=product&promo_external_id=promo_set_default_product&show_cta=true

Should be an optional field.

**Comment by hoyelo** [comment]
@diptib10 @AmyBeall Pls check this PR #12 ,thanks!
