### ISSUE TITLE
Affirm SDK doesn't build in Xcode 15 (when imported via Cocoapods)

### ISSUE THREAD

**Issue by iOSSoftwareEngineer** [Affirm/affirm-merchant-sdk-ios#135]
When you use Cocoapods to include the Affirm SDK as part of your app, the Affirm SDK won't build in Xcode 15.

**Comment by hoyelo** [comment]
@iOSSoftwareEngineer You can fix it by updating your Xcode project build option 'ENABLE_USER_SCRIPT_SANDBOXING' to 'No'.
