### ISSUE TITLE
Unexpected CFBundleExecutable Key in bundle Info.plist

### ISSUE THREAD

**Issue by rzulkoski** [Affirm/affirm-merchant-sdk-ios#17]
When attempting to upload a build to the App Store, I received the following error from the iTMSTransporter:

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Storefront.app/Frameworks/AffirmSDK.framework/AffirmSDK.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Any help would be greatly appreciated. Thanks!

**Comment by rzulkoski** [comment]
This was built using Carthage. I noticed that the old [affirm-ios-sdk](https://github.com/Affirm/affirm-ios-sdk) project included `affirm-ios-sdk/AffirmSDK/Carthage/Info.plist`. Would that fix this issue?

**Comment by hoyelo** [comment]
@rzulkoski I have fixed this issue by removing the unexpected key.
@AmyBeall Because it can't be tested, I'm just going to update the code directly to the master branch.

**Comment by rzulkoski** [comment]
After pointing at your commit on master, I now get this error when trying to run our app:

![Screen Shot 2019-05-10 at 8 52 46 AM](https://user-images.githubusercontent.com/3171325/57532368-1e2df280-7301-11e9-8588-01d5f8d59bac.png)

**Comment by rzulkoski** [comment]
@hoyelo @AmyBeall I created a pull request implementing the [same fixes](https://github.com/Affirm/affirm-ios-sdk/commit/6aeaf00866a91d9f9f9182b8c67dd1ce96fd7ac2#diff-adcd6e9e76a7b5358d25953aed345b6b) that were applied to the original affirm-ios-sdk. I can confirm that I was able to successfully upload to the App Store with these changes applied.

**Comment by rzulkoski** [comment]
I create #18 to fix this issue. Could you review my pull request?
