### ISSUE TITLE
The layout of the checkout page gets cluttered

### ISSUE THREAD

**Issue by hoyelo** [Affirm/affirm-merchant-sdk-ios#2]
<img width="529" alt="iOS___Android_sdk_rewrite_ready_for_test_-_steve_interactivelabs_co_-_Interactive_Labs__Inc_Mail(2)" src="https://user-images.githubusercontent.com/3202811/56338944-c9ee9180-61de-11e9-8779-87e7d871277e.png">
<img width="522" alt="iOS___Android_sdk_rewrite_ready_for_test_-_steve_interactivelabs_co_-_Interactive_Labs__Inc_Mail(3)" src="https://user-images.githubusercontent.com/3202811/56338947-ceb34580-61de-11e9-9466-b304ed3c8ce5.png">
@nandadubey Can you tell from the screenshot which device it might be?

**Comment by AmyBeall** [comment]
The device is iPhone SE

**Comment by hoyelo** [comment]
Thanks @AmyBeall @nandadubey 
I had reproduce the same issue on iPhone 5S, i think it's related to all of devices with small screens (Including android and ios devices). Also it appears in the old affirm demo. To fix it, we have to get the help from your web developer because it's a web issue.

**Comment by AmyBeall** [comment]
OK thanks for looking into this, I'll look into it on our end
