### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by AmyBeall** [Affirm/affirm-merchant-sdk-ios#42]
@hoyelo @sichx 
I am having issues building the Example App. The pod, AffirmSDK, is not found. I have tried running `pod deintegrate` and then `pod install` but it is still not installing the AffirmSDK pod. Please help to resolve this issue:
![image](https://user-images.githubusercontent.com/8650185/65175075-fbc28900-da06-11e9-8025-e21247a42868.png)

**Comment by sichx** [comment]
@AmyBeall we are thinking this might be a cocoapods version issue.  We reproduced it on cocoapods 1.5

We will try this first and see if it fixes it for you.

**Comment by hoyelo** [comment]
@AmyBeall Issue fixed, pls check this PR: https://github.com/Affirm/affirm-merchant-sdk-ios/pull/43

**Comment by AmyBeall** [comment]
Thanks! It's working now
