### ISSUE TITLE
`AffirmDataHandler.getPromoMessageWithPromoID` crash

### ISSUE THREAD

**Issue by andrewfoghel** [Affirm/affirm-merchant-sdk-ios#50]
I ran into a crash when using the `AffirmDataHandler.getPromoMessageWithPromoID` I didn't look too deep into it, but the crash happens when you pass in `UIFont()` to the `font` parameter of the method. However, if you specify a font size then the crash doesn't occur.

**Comment by hoyelo** [comment]
@andrewfoghel Fixed in this PR: [https://github.com/Affirm/affirm-merchant-sdk-ios/pull/57](https://github.com/Affirm/affirm-merchant-sdk-ios/pull/57)
