### ISSUE TITLE
Add user cookie for dynamic ala button text

### ISSUE THREAD

**Issue by AmyBeall** [Affirm/affirm-merchant-sdk-ios#6]
@sichx can we add support for the dynamic ala button text in iOS as well?

**Comment by sichx** [comment]
@AmyBeall we looked into this yesterday and here is a small question we are facing.   We are currently using WKWebview as our webview container, as UIWebview is being deprecated.  Getting cookies from WKWebview, however, is only available after [iOS 11](https://stackoverflow.com/a/44762378).  

If we want this implemented, I can think of two ways to do it:

1. Make this a conditional feature for iOS 11 and up
2. Up the OS requirement from 9 to 11

(My vote goes to option 1)

Interested to hear your take / preference on this?  

cc @nandadubey @hoyelo

**Comment by hoyelo** [comment]
@nandadubey  https://github.com/Affirm/affirm-merchant-sdk-ios/pull/8

**Comment by AmyBeall** [comment]
@sichx How much work would be required for option 2?

**Comment by sichx** [comment]
@AmyBeall not much at all, though it means the integration partners won't be able to go below iOS 11 on their apps too, if that's okay.

**Comment by AmyBeall** [comment]
@sichx got it, in this case option 1 is better. How much effort would it be to create cookies for versions below 11?

**Comment by sichx** [comment]
Okay.  Although it's possible to do it in version < 11, the class / method (UIWebView) is deprecated...if we really want to do it, we will also need to use the same deprecated UIWebView for the prequal flow. It will take roughly 0.5-1 day.

**Comment by sichx** [comment]
@hoyelo please also check this out for sharing cookies in `WKWebView`:

https://stackoverflow.com/questions/25797972/cookie-sharing-between-multiple-wkwebviews

**Comment by hoyelo** [comment]
Thanks @sichx , i had checked with WKProcessPool, but it's only valid for current loop, if app killed and relaunched, all of cookies for webview will be lost (No way to persist WKProcessPool). 
Now using WKProcessPool for webview, then get cookies from webview and share them to api request (only available after ios11). @AmyBeall  Pls see whether it's okay on #8 .

**Comment by sichx** [comment]
@hoyelo good to know, @AmyBeall let us know if we could stick to this for now and not do anything fancy like persisting our own cookie jar?

**Comment by AmyBeall** [comment]
@sichx @hoyelo This should work for now, thank you

**Comment by AmyBeall** [comment]
@sichx @hoyelo during black box testing it appears that the cookie does not persist from prequal to checkout. What is required to make that work?

**Comment by hoyelo** [comment]
@AmyBeall @sichx Pls check the two gists, one ala request after prequal flow and one after checkout flow.
https://gist.github.com/hoyelo/0895e8ade57adfb15e51870843f8ae42
https://gist.github.com/hoyelo/841323119d209517ca0f158077525f0b
After checkout flow, the cookies seem not work for ala request.

**Comment by hoyelo** [comment]
@AmyBeall I have just verified it and recorded a video, pls check [this link](http://recordit.co/4bNNPL7Rv7).
Do you mean the test cases? If yes, the app will be killed and relaunched for each case, so the cookie doesn't persist.

**Comment by AmyBeall** [comment]
@hoyelo there was a build or cache issue on my end. I got it working. Thanks for all of your help!
