### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by ghost** [Affirm/affirm-merchant-sdk-ios#95]
It would be good to add Swift package manager support. So that affirm dependency can be added using Xcode in a more Apple's way

**Comment by bbernberg** [comment]
+1!

**Comment by ghost** [comment]
@bbernberg I have created a PR https://github.com/Affirm/affirm-merchant-sdk-ios/pull/96

**Comment by ghost** [comment]
PR #96 is merged. So closing this issue
