### ISSUE TITLE
Swift Package Manager error on XCode 12.5

### ISSUE THREAD

**Issue by bbernberg** [Affirm/affirm-merchant-sdk-ios#99]
I am getting the following error when attempting to install the SDK using SPM

<img width="586" alt="Screen Shot 2021-05-19 at 9 34 05 AM" src="https://user-images.githubusercontent.com/1385086/118822101-dba33700-b885-11eb-8757-6c231ce2db03.png">

**Comment by thillsman** [comment]
Same here. 👍🏼

**Comment by ghost** [comment]
Opened the PR to resolve this issue https://github.com/Affirm/affirm-merchant-sdk-ios/pull/103
